# Generated by Django 2.0.3 on 2018-03-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_fixed', models.FloatField()),
                ('price_fractioned', models.FloatField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
