version: '2'
services:
  postgres:
    image: ambientum/postgres:9.6
    container_name: server-postgres-olist
    volumes:
      - olist-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_DB=olist
      - POSTGRES_USER=olist

volumes:
  # Postgres Data
  olist-postgres-data:
    driver: local