# Generated by Django 2.0.3 on 2018-03-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=10)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('call_id_external', models.TextField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
            ],
        ),
    ]
